spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventManager
    username: postgres
    password: 123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: ${JWT_SECRET:event-manager-key}