spring:
  datasource:
    url: jdbc:mysql://154.56.48.204:3306/u831664360_eventmanager
    username: u831664360_eventmanager
    password: O^7b499t
    driver-class-name: com.mysql.jdbc.Driver

api:
  security:
    token:
      secret: ${JWT_SECRET:event-manager-key}