name: Deploy EventManager to GCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/eventmanager:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK    
        uses: actions/setup-java@v1      
        with:        
         java-version: 1.19
         
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build with Gradle      
        run: gradle build

      - name: Build the Spring Project
        run: docker build -t $IMAGE_NAME .

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build the Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy eventmanager --image $IMAGE_NAME --region us-central1 --memory 650Mi --min-instances 0 --max-instances 1 --platform managed --port 8080 --allow-unauthenticated
